# Generated by Django 3.2.12 on 2022-03-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('username', models.TextField()),
                ('gender', models.TextField()),
                ('email', models.TextField()),
                ('contactno', models.TextField()),
                ('password', models.TextField()),
                ('zipcode', models.TextField()),
                ('subject', models.TextField()),
            ],
        ),
    ]
