# Generated by Django 3.2.12 on 2022-04-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_Teachers_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_username', models.TextField()),
                ('student_username', models.TextField()),
                ('subject', models.TextField()),
            ],
        ),
    ]
