# Generated by Django 3.2.12 on 2022-04-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_connection_counts_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('subscription_type', models.TextField()),
            ],
        ),
    ]
