# Generated by Django 3.2.12 on 2022-04-12 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_subscription_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_entries',
            name='subscription_start_date',
            field=models.DateTimeField(default=datetime.date(2022, 4, 13)),
        ),
    ]
