# Generated by Django 3.2.12 on 2022-04-26 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_auto_20220413_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_image', models.ImageField(upload_to='pics')),
                ('course_desc', models.TextField()),
                ('course_count', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='subscription_entries',
            name='subscription_start_date',
            field=models.DateTimeField(default=datetime.date(2022, 4, 26)),
        ),
    ]
